name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  rs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: Cargo Build
        with:
          command: build
          args: --verbose --features std
      - uses: actions-rs/cargo@v1
        name: Cargo Test
        with:
          command: test
          args: --verbose --features std
      - name: Cache Cargo Registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ubuntu-latest-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
  js-test:
    runs-on: ubuntu-latest
    needs:
      - rs-test
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, v14.18.3, 14.x, 16.x, 18.x, '*' ]
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: Install WasmPack
        with:
          command: install
          args: wasm-pack
      - uses: actions/setup-node@v1
        name: Setup Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v3.0.0
        name: Install npm dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Run Jest Tests
        with:
          cmd: run test
      - name: Cache Cargo Registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ubuntu-latest-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
  assemble:
    runs-on: ubuntu-latest
    needs:
      - js-test
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: 18.x
      - uses: actions-rs/toolchain@v1
        name: Setup Rust
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        name: Install WasmPack
        with:
          command: install
          args: wasm-pack
      - uses: borales/actions-yarn@v3.0.0
        name: Install npm dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Build
        with:
          cmd: run build
      - uses: actions/upload-artifact@v2
        name: Upload Artifacts
        with:
          name: pkg
          path: |
            pkg.bundler/
            pkg.node/
            pkg.web/
            package.json
            index.browser.js
            LICENCE
            README.md
      - name: Cache Cargo Registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ubuntu-latest-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
  js-test-integration:
    runs-on: ubuntu-latest
    needs:
      - assemble
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, v14.18.3, 14.x, 16.x, 18.x, '*' ]
    steps:
      - uses: actions/checkout@v2
        name: Clone
      - uses: actions/download-artifact@master
        with:
          name: pkg
      - uses: actions/setup-node@v1
        name: Setup Node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v3.0.0
        name: Install npm dependencies
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: Run Jest Tests
        with:
          cmd: run test:integration